version: "3"

services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    restart: always
    ports:
      - 3000:3000
    networks:
      - app_network
      - db
  db:
    platform: linux/amd64
    image: mysql:8.0.32
    container_name: application_mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: application_db
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - database:/var/lib/mysql

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  app_network:
    external: true

volumes:
  database:
    driver: local